version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "chart_project.wsgi:application" ]

  frontend:
    build:
      context: ./frontend/chart-project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/chart-project:/app
    environment:
      - NODE_ENV=development
