services:
  backend:
    build:
      context: ./backend/chart_project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chart_project:/app
    environment:
      - DEBUG=True
    command: [ "gunicorn", "--bind", "0.0.0.0:8000", "chart_project.wsgi:application" ]

  frontend:
    build:
      context: ./frontend/chart-project
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    # volumes:
    #   - ./frontend/chart-project:/app
    environment:
      - NODE_ENV=development
